version: "3"

services:
  mongo:
    image: mongo:4.2.3
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
  mongo-dump:
      build: .
      # command: ["./entrypoint.sh", "restore"]
      environment: 
        - MONGO_URL=mongodb://mongo:27017/db
      volumes:
        - ./backup:/backup
